### ISSUE TITLE
Working on a Gazebo Harmonic port of this package, change of license?

### ISSUE THREAD

**Issue by Mechazo11** [mgonzs13/ros2_asus_xtion#2]
Hi @mgonzs13 

Thank you very much for making a ROS 2 compliant package to interface Asus Xiton RGBD cameras. I am working on a Gazebo Harmonic compliant port of this package for my UGV [simulator](https://github.com/Mechazo11/clearpath_simulator_harmonic) based on the UGV simulator by Clearpath Robotics.

I was wondering if you would consider changing the license to ```MIT```. ```Apache 2.0``` or ? I have been working the ```space-ros``` community for sometime now and it is there where I learned that GPL-3 while being permissive for academia goes in odds with the ```MIT```, ```Apache 2.0``` or ```BSD-3``` license, the former requiring any software stack utilizing a GPL-3 license to also have their entire stack's license to GPL-3. 

While maybe this is not real an issue I still wanted to get your thoughts on this nonetheless.

Best regards,
@Mechazo11

**Comment by mgonzs13** [comment]
Hi @Mechazo11, since there is an incoming update to replace the submodule, I can consider changing also the license.

**Comment by mgonzs13** [comment]
@Mechazo11 please, take a look to the new changes.

**Comment by Mechazo11** [comment]
Awesome @mgonzs13 I will go ahead and close this ticket. I will also move all the licenses of my fork to BSD-3. Will leave a link in another ticket once I am done testing the camera in Gazebo Harmonic.

With best,
@Mechazo11
